// Auto-generated by scripts/fetch_club_logos.mjs.
// Re-run that script when Sejm clubs change. Logos live in public/club-logos/.
export type ClubLogoEntry = { file: string; name: string; members: number | null };
export const CLUB_LOGOS: Record<string, ClubLogoEntry> = {
  "Centrum": {
    "file": "Centrum.jpg",
    "name": "Klub Parlamentarny Centrum",
    "members": 15
  },
  "Demokracja": {
    "file": "Demokracja.jpg",
    "name": "Koło Poselskie Demokracja Bezpośrednia",
    "members": 4
  },
  "KO": {
    "file": "KO.jpg",
    "name": "Klub Parlamentarny Koalicja Obywatelska - Platforma Obywatelska, Nowoczesna, Inicjatywa Polska, Zieloni",
    "members": 156
  },
  "Konfederacja": {
    "file": "Konfederacja.jpg",
    "name": "Klub Poselski Konfederacja",
    "members": 16
  },
  "Konfederacja_KP": {
    "file": "Konfederacja_KP.jpg",
    "name": "Koło Poselskie Konfederacja Korony Polskiej",
    "members": 3
  },
  "Lewica": {
    "file": "Lewica.jpg",
    "name": "Koalicyjny Klub Parlamentarny Lewicy (Nowa Lewica, PPS, Unia Pracy)",
    "members": 20
  },
  "PiS": {
    "file": "PiS.jpg",
    "name": "Klub Parlamentarny Prawo i Sprawiedliwość",
    "members": 187
  },
  "Polska2050": {
    "file": "Polska2050.jpg",
    "name": "Klub Parlamentarny Polska 2050",
    "members": 15
  },
  "PSL-TD": {
    "file": "PSL-TD.jpg",
    "name": "Klub Parlamentarny Polskie Stronnictwo Ludowe - Trzecia Droga",
    "members": 32
  },
  "Razem": {
    "file": "Razem.jpg",
    "name": "Koło Poselskie Razem",
    "members": 4
  }
};
