// Fetch every term-10 klub logo from the Sejm API into `public/club-logos/`.
// Run on demand: `node scripts/fetch_club_logos.mjs`. Output is committed so
// the production build stays self-contained (no runtime fetch from sejm.gov.pl).

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const TERM = 10;
const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT = join(ROOT, "..", "public", "club-logos");
mkdirSync(OUT, { recursive: true });

const extFor = (mime) => {
  if (!mime) return "png";
  if (mime.includes("svg")) return "svg";
  if (mime.includes("jpeg") || mime.includes("jpg")) return "jpg";
  if (mime.includes("gif")) return "gif";
  return "png";
};

const clubs = await fetch(`https://api.sejm.gov.pl/sejm/term${TERM}/clubs`).then((r) => r.json());
const manifest = {};
for (const c of clubs) {
  const url = `https://api.sejm.gov.pl/sejm/term${TERM}/clubs/${encodeURIComponent(c.id)}/logo`;
  const res = await fetch(url);
  if (!res.ok) {
    console.warn(`skip ${c.id}: ${res.status}`);
    continue;
  }
  const mime = res.headers.get("content-type") || "";
  const ext = extFor(mime);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 200) {
    // Sejm returns 0-byte responses for clubs without an uploaded logo (e.g. niez.).
    console.warn(`skip ${c.id}: empty body (${buf.length}B)`);
    continue;
  }
  // Sanitize id for filename (only "niez." has a dot; replace with "_").
  const safe = c.id.replace(/[^a-zA-Z0-9_-]/g, "_");
  const file = `${safe}.${ext}`;
  writeFileSync(join(OUT, file), buf);
  manifest[c.id] = { file, name: c.name, members: c.membersCount ?? null };
  console.log(`✓ ${c.id} → ${file} (${buf.length}B, ${mime})`);
}

// Emit a TS module the components can import (no JSON-import hassle).
const tsOut = join(ROOT, "..", "lib", "atlas", "club-logos.ts");
const ts = `// Auto-generated by scripts/fetch_club_logos.mjs.
// Re-run that script when Sejm clubs change. Logos live in public/club-logos/.
export type ClubLogoEntry = { file: string; name: string; members: number | null };
export const CLUB_LOGOS: Record<string, ClubLogoEntry> = ${JSON.stringify(manifest, null, 2)};
`;
writeFileSync(tsOut, ts);
console.log(`\nwrote ${tsOut} with ${Object.keys(manifest).length} clubs`);
