"""Build frontend/lib/atlas/okregi-shapes.ts from sejm-complete-41.json.

Source: Konstantysz/voting-optimizer (Apache-2.0), already used by
supagraf.fixtures.sources.postcodes for postcode->district join.

Pipeline:
  1. Load 41-feature FeatureCollection from scripts/data/sejm-complete-41.json
  2. Per feature: shapely-simplify each polygon ring to match voivodeship
     tolerance (~0.012 deg, Douglas-Peucker), preserve topology
  3. Compute representative point (point_on_surface) for label placement
  4. Emit TS module mirroring poland-shapes.ts style

Run:
    uv run --with shapely python scripts/build_okregi_shapes.py
"""
from __future__ import annotations

import json
from pathlib import Path

from shapely.geometry import shape, mapping
from shapely.ops import transform

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "data" / "sejm-complete-41.json"
OUT = ROOT / "frontend" / "lib" / "atlas" / "okregi-shapes.ts"

TOLERANCE_DEG = 0.012  # matches DP tolerance used for voivodeships
COORD_PRECISION = 4    # ~11m at PL latitude


def round_coords(geom):
    return transform(lambda x, y, z=None: (round(x, COORD_PRECISION), round(y, COORD_PRECISION)), geom)


def rings_from_geom(geom) -> list[list[tuple[float, float]]]:
    """Return list of outer rings (no holes — okręgi don't have enclaves)."""
    g = geom.geom_type
    if g == "Polygon":
        return [list(geom.exterior.coords)]
    if g == "MultiPolygon":
        return [list(p.exterior.coords) for p in geom.geoms]
    raise ValueError(f"unexpected geom type: {g}")


def main() -> None:
    fc = json.loads(SRC.read_text(encoding="utf-8"))
    features = sorted(fc["features"], key=lambda f: int(f["properties"]["id"]))

    out_entries: list[str] = []
    total_pts_raw = 0
    total_pts_out = 0

    for f in features:
        oid = int(f["properties"]["id"])
        name = f["properties"].get("name", f"Okręg {oid}")
        g = shape(f["geometry"])

        # raw point count
        raw = sum(len(r) for r in rings_from_geom(g))
        total_pts_raw += raw

        # simplify + round
        gs = g.simplify(TOLERANCE_DEG, preserve_topology=True)
        gs = round_coords(gs)
        if not gs.is_valid:
            gs = gs.buffer(0)

        rings = rings_from_geom(gs)
        out_pts = sum(len(r) for r in rings)
        total_pts_out += out_pts

        # representative point (guaranteed inside the polygon, even concave)
        rp = gs.representative_point()
        cx, cy = round(rp.x, COORD_PRECISION), round(rp.y, COORD_PRECISION)

        # emit ts
        rings_ts = ",".join(
            "[" + ",".join(f"[{x},{y}]" for x, y in r) + "]" for r in rings
        )
        out_entries.append(
            f'  {{ id: {oid}, name: {json.dumps(name, ensure_ascii=False)}, '
            f'centroid: [{cx},{cy}], rings: [{rings_ts}] }}'
        )
        print(f"#{oid:>2} {name:<20} raw={raw:>4} -> simp={out_pts:>3}")

    print(f"\ntotal pts: {total_pts_raw} -> {total_pts_out}")

    header = (
        "// Auto-generated by scripts/build_okregi_shapes.py.\n"
        "// Source: Konstantysz/voting-optimizer (Apache-2.0) sejm-complete-41.json,\n"
        f"// derived from GeoElections Poland 1.0. DP-simplified to ~{TOLERANCE_DEG} deg.\n"
        "// Each entry has outer rings only (no holes — okręgi have no enclaves).\n"
        "// MultiPolygon okręgi (e.g. #41 Szczecin with islands) emit one ring per polygon.\n"
        "export type OkregPolygon = {\n"
        "  id: number;\n"
        "  name: string;\n"
        "  centroid: [number, number];\n"
        "  rings: Array<Array<[number, number]>>;\n"
        "};\n"
        "export const OKREGI_POLYGONS: OkregPolygon[] = [\n"
    )
    body = ",\n".join(out_entries)
    footer = "\n];\n"

    OUT.write_text(header + body + footer, encoding="utf-8")
    print(f"\nwrote {OUT}")
    print(f"size: {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
